# -*- coding: utf-8 -*-
"""firebase/firebase_setup

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yQNgG9DGxzP-8HwoQQqX4Dmu32hqps2Q
"""

import firebase_admin
from firebase_admin import credentials, firestore

cred = credentials.Certificate("firebase-key.json")  # 🔐 Replace with placeholder
firebase_admin.initialize_app(cred)
db = firestore.client()

def add_to_firebase(patient_id, summary):
    db.collection("patients").document(str(patient_id)).set({"summary": summary})