# -*- coding: utf-8 -*-
"""pyspark/preprocess

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yQNgG9DGxzP-8HwoQQqX4Dmu32hqps2Q
"""

from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("Healthcare").getOrCreate()
df = spark.read.csv("disease_diagnosis.csv", header=True, inferSchema=True)
df.show()