# -*- coding: utf-8 -*-
"""tensorflow/summarize.py python Copy code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yQNgG9DGxzP-8HwoQQqX4Dmu32hqps2Q
"""

import openai

openai.api_key = "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"
def summarize_patient_history(data_dict):
    prompt = f"Patient data: {data_dict}. Summarize the condition and suggest a treatment."
    response = openai.ChatCompletion.create(
        model="gpt-4",
        messages=[{"role": "user", "content": prompt}]
    )
    return response['choices'][0]['message']['content']